name: MonTest
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: Version de la publication
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 290
          - 291
          - 292
          - 293
          - 294
          - 354
    steps:
      - name: Coin
        run: echo "Coin ${{ matrix.version }}"
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Affichage
        run: echo ${{ jobs.build.env }}

      - name: Affichage 2
        run: echo ${{ toJson(jobs.build.env) }}
